<?php

namespace AppBundle\Repository;

/**
 * ActualOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
