<?php

namespace AppBundle\Repository;

/**
 * ForecastInboundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastInboundRepository extends \Doctrine\ORM\EntityRepository
{
}
