<?php

namespace AppBundle\Repository;

/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends \Doctrine\ORM\EntityRepository
{
}
