<?php

namespace AppBundle\Repository;

/**
 * openingBalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningBalanceRepository extends \Doctrine\ORM\EntityRepository
{
}
