<?php

namespace AppBundle\Repository;

/**
 * ProductivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductivityRepository extends \Doctrine\ORM\EntityRepository
{
}
