<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalesOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderRepository extends EntityRepository
{
    public function deleteAll()
    {
        $this->getEntityManager()->createQuery('DELETE FROM AppBundle:SalesOrder')
        ->execute();
    }
}
